title: 简历 - CFD 开发工程师 - 闻韬

aboutme:
  name: 闻韬 / Tao Wen
  sex: 男
  age: 25
  email: i@lanceir.com
  phone: 17865197931
  github: https://github.com/lanceir
  city: 北京
  university: 中国科学院大学 / Technical University of Danmark 
  edu: 硕士
  research: CFD，IBM，煤燃烧

update: 2020年05月25日
